// Flat ESLint config for this service's backend. Kept deliberately small:
// `@typescript-eslint/recommended` for real correctness signal, with
// `no-explicit-any` off (the error/plugin plumbing uses `any` deliberately),
// plus a disable-abuse guard so the gate can't be silently switched off.
//
// Generated and regenerated by stackr — edits are overwritten. The PostToolUse
// hook (.claude/hooks/check-edited.mjs) runs this on each edited file once
// dependencies are installed.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import comments from '@eslint-community/eslint-plugin-eslint-comments';

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'prisma/generated/**',
      'drizzle/**',
      'eslint.config.mjs',
      '*.config.ts',
      '*.config.mjs',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    plugins: { '@eslint-community/eslint-comments': comments },
    linterOptions: { reportUnusedDisableDirectives: 'error' },
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
      // Ban a bare `// eslint-disable` (no rule list) so the gate stays honest.
      '@eslint-community/eslint-comments/no-unlimited-disable': 'error',
    },
  },
);
