import YAML from 'yaml';
import type { StackrConfigFile, ServiceEntry } from '../types/config-file.js';
import { initComposeWithMarkedBlocks } from '../utils/compose-merge.js';

/**
 * Programmatic docker-compose.yml renderer. See
 * `plans/phase2_multi_service_generation.md` §D.3 for fidelity
 * requirements and the reference shape in
 * `/Users/ghost/Documents/FRC 9483/team9483-stack/docker-compose.yml`.
 *
 * Strategy: we serialize individual service/volume entries via
 * `yaml.stringify` (so docker-compose fields stay quoted/escaped
 * correctly) then assemble the top-level file by hand so the marker
 * comments land at the right indent. The `services:` / `volumes:` top-
 * level keys live OUTSIDE the marker block; only the managed entries are
 * inside — this is what lets phase 3's preservation contract work.
 *
 * Output is byte-deterministic for identical inputs (sorted nowhere —
 * iteration order is `config.services[]`).
 */
export function renderDockerCompose(
  config: StackrConfigFile,
  mode: 'dev' | 'prod'
): string {
  if (mode === 'dev') {
    return renderDevCompose(config);
  }
  return renderProdCompose(config);
}

// ---------------------------------------------------------------------------
// Dev compose
// ---------------------------------------------------------------------------

function renderDevCompose(config: StackrConfigFile): string {
  const { services: cfgServices, projectName } = config;

  // Compute per-service external ports so DB/Redis don't collide.
  const portMap = assignInfraPorts(cfgServices);
  const authService = cfgServices.find((s) => s.kind === 'auth') ?? null;

  // Build services map in deterministic order, flattening each service's
  // 2-4 compose entries (db, redis?, rest_api, event_queue?).
  const serviceBlocks: string[] = [];
  const volumeBlocks: string[] = [];

  for (const svc of cfgServices) {
    const ports = portMap[svc.name];

    serviceBlocks.push(
      renderServiceDbBlock(svc, ports, projectName, 'dev')
    );

    const needsRedis = svc.backend.eventQueue || svc.backend.imageUploads || true;
    if (needsRedis) {
      serviceBlocks.push(
        renderServiceRedisBlock(svc, ports, projectName, 'dev')
      );
    }

    serviceBlocks.push(
      renderServiceRestApiBlock(svc, ports, projectName, 'dev', authService)
    );

    if (svc.backend.eventQueue) {
      serviceBlocks.push(
        renderServiceEventQueueBlock(svc, projectName, 'dev')
      );
    }

    // Volume entries
    volumeBlocks.push(`  ${svc.name}_postgres_data:\n    driver: local\n`);
    if (needsRedis) {
      volumeBlocks.push(`  ${svc.name}_redis_data:\n    driver: local\n`);
    }
  }

  const serviceEntries = serviceBlocks.join('\n');
  const volumeEntries = volumeBlocks.join('');

  const header =
    `# All infrastructure for local development\n` +
    `# Usage: docker compose up -d\n` +
    `# Managed by stackr — marker blocks below are regenerated by\n` +
    `# \`stackr add service\`. Edit OUTSIDE the markers to preserve work.\n`;

  return initComposeWithMarkedBlocks(serviceEntries, volumeEntries, { header });
}

// ---------------------------------------------------------------------------
// Prod compose (overlay)
// ---------------------------------------------------------------------------

function renderProdCompose(config: StackrConfigFile): string {
  const { services: cfgServices } = config;
  const portMap = assignInfraPorts(cfgServices);

  const serviceBlocks: string[] = [];

  for (const svc of cfgServices) {
    const ports = portMap[svc.name];

    // db
    serviceBlocks.push(
      indentEntry(
        `${svc.name}_db:\n` +
          `  restart: always\n` +
          `  ports:\n` +
          `    - "127.0.0.1:${ports.db}:5432"\n` +
          `  healthcheck:\n` +
          `    interval: 30s\n` +
          `    timeout: 5s\n` +
          `    retries: 5\n`
      )
    );

    // redis
    serviceBlocks.push(
      indentEntry(
        `${svc.name}_redis:\n` +
          `  restart: always\n` +
          `  ports:\n` +
          `    - "127.0.0.1:${ports.redis}:6379"\n` +
          `  healthcheck:\n` +
          `    interval: 30s\n` +
          `    timeout: 5s\n` +
          `    retries: 5\n` +
          `  deploy:\n` +
          `    resources:\n` +
          `      limits:\n` +
          `        memory: 512M\n` +
          `      reservations:\n` +
          `        memory: 256M\n`
      )
    );

    // rest api
    serviceBlocks.push(
      indentEntry(
        `${svc.name}_rest_api:\n` +
          `  build:\n` +
          `    context: ./${svc.name}/backend\n` +
          `    target: rest-api-prod\n` +
          `    dockerfile: Dockerfile\n` +
          `  restart: always\n` +
          `  environment:\n` +
          `    NODE_ENV: production\n` +
          `    LOG_LEVEL: \${LOG_LEVEL:-info}\n` +
          `  ports:\n` +
          `    - "127.0.0.1:${svc.backend.port}:${svc.backend.port}"\n` +
          `  volumes: []\n` +
          `  healthcheck:\n` +
          `    test: ["CMD", "bun", "-e", "const res = await fetch('http://localhost:${svc.backend.port}/'); process.exit(res.ok ? 0 : 1)"]\n` +
          `    interval: 30s\n` +
          `    timeout: 10s\n` +
          `    retries: 3\n` +
          `    start_period: 30s\n`
      )
    );

    if (svc.backend.eventQueue) {
      serviceBlocks.push(
        indentEntry(
          `${svc.name}_event_queue:\n` +
            `  build:\n` +
            `    context: ./${svc.name}/backend\n` +
            `    target: event-queue-prod\n` +
            `    dockerfile: Dockerfile\n` +
            `  restart: always\n` +
            `  environment:\n` +
            `    NODE_ENV: production\n` +
            `    LOG_LEVEL: \${LOG_LEVEL:-info}\n` +
            `  volumes: []\n`
        )
      );
    }
  }

  const serviceEntries = serviceBlocks.join('\n');
  // Prod overlay has no managed volumes section (volumes come from dev).
  const header =
    `# Production overlay for docker-compose.yml\n` +
    `# Usage: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d\n` +
    `# Managed by stackr — marker blocks below are regenerated by\n` +
    `# \`stackr add service\`. Edit OUTSIDE the markers to preserve work.\n`;

  return initComposeWithMarkedBlocks(serviceEntries, '', { header });
}

// ---------------------------------------------------------------------------
// Shared block renderers
// ---------------------------------------------------------------------------

interface InfraPorts {
  db: number; // published DB port on host (Postgres)
  redis: number; // published Redis port on host
}

/**
 * Assign external host ports for each service's Postgres and Redis in
 * declaration order, starting at 5432 / 6379 and incrementing.
 */
function assignInfraPorts(services: readonly ServiceEntry[]): Record<string, InfraPorts> {
  const out: Record<string, InfraPorts> = {};
  let dbPort = 5432;
  let redisPort = 6379;
  for (const svc of services) {
    out[svc.name] = { db: dbPort++, redis: redisPort++ };
  }
  return out;
}

function renderServiceDbBlock(
  svc: ServiceEntry,
  ports: InfraPorts,
  projectName: string,
  _mode: 'dev' | 'prod'
): string {
  const upper = envPrefix(svc.name);
  const defaultDbName = `${projectName}_${svc.name}`.replace(/-/g, '_');

  return indentEntry(
    `${svc.name}_db:\n` +
      `  image: postgres:16-alpine\n` +
      `  container_name: ${projectName}-${svc.name}_db\n` +
      `  restart: unless-stopped\n` +
      `  environment:\n` +
      `    POSTGRES_USER: \${${upper}_DB_USER:-postgres}\n` +
      `    POSTGRES_PASSWORD: \${${upper}_DB_PASSWORD}\n` +
      `    POSTGRES_DB: \${${upper}_DB_NAME:-${defaultDbName}}\n` +
      `  ports:\n` +
      `    - "${ports.db}:5432"\n` +
      `  volumes:\n` +
      `    - ${svc.name}_postgres_data:/var/lib/postgresql/data\n` +
      `  healthcheck:\n` +
      `    test: ["CMD-SHELL", "pg_isready -U \${${upper}_DB_USER:-postgres} -d \${${upper}_DB_NAME:-${defaultDbName}}"]\n` +
      `    interval: 10s\n` +
      `    timeout: 5s\n` +
      `    retries: 3\n`
  );
}

function renderServiceRedisBlock(
  svc: ServiceEntry,
  ports: InfraPorts,
  projectName: string,
  _mode: 'dev' | 'prod'
): string {
  const upper = envPrefix(svc.name);
  return indentEntry(
    `${svc.name}_redis:\n` +
      `  image: redis:7-alpine\n` +
      `  container_name: ${projectName}-${svc.name}_redis\n` +
      `  restart: unless-stopped\n` +
      `  command: redis-server --appendonly yes --requirepass \${${upper}_REDIS_PASSWORD:-redis-password}\n` +
      `  ports:\n` +
      `    - "${ports.redis}:6379"\n` +
      `  volumes:\n` +
      `    - ${svc.name}_redis_data:/data\n` +
      `  healthcheck:\n` +
      `    test: ["CMD", "redis-cli", "--raw", "incr", "ping"]\n` +
      `    interval: 10s\n` +
      `    timeout: 3s\n` +
      `    retries: 3\n`
  );
}

function renderServiceRestApiBlock(
  svc: ServiceEntry,
  _ports: InfraPorts,
  projectName: string,
  _mode: 'dev' | 'prod',
  authService: ServiceEntry | null
): string {
  const upper = envPrefix(svc.name);
  const defaultDbName = `${projectName}_${svc.name}`.replace(/-/g, '_');
  const authServiceUrl = authService
    ? `http://${authService.name}_rest_api:${authService.backend.port}`
    : null;

  // All environment and depends_on lines are at 4-space indent *before*
  // indentEntry adds its own 2-space prefix — final indent is 6 spaces
  // which sits one level deeper than the parent `environment:` / `depends_on:` keys.
  const envLines: string[] = [
    `    NODE_ENV: development`,
    `    DATABASE_URL: postgresql://\${${upper}_DB_USER:-postgres}:\${${upper}_DB_PASSWORD}@${svc.name}_db:5432/\${${upper}_DB_NAME:-${defaultDbName}}`,
    `    API_HOST: 0.0.0.0`,
    `    API_PORT: ${svc.backend.port}`,
    `    LOG_LEVEL: debug`,
    `    REDIS_HOST: ${svc.name}_redis`,
    `    REDIS_PORT: 6379`,
    `    REDIS_PASSWORD: \${${upper}_REDIS_PASSWORD:-redis-password}`,
  ];

  if (authServiceUrl && svc.kind !== 'auth') {
    envLines.push(`    AUTH_SERVICE_URL: ${authServiceUrl}`);
  }

  const dependsLines: string[] = [
    `    ${svc.name}_db:`,
    `      condition: service_healthy`,
    `    ${svc.name}_redis:`,
    `      condition: service_healthy`,
  ];

  if (authServiceUrl && svc.kind !== 'auth') {
    dependsLines.push(`    ${authService!.name}_rest_api:`);
    dependsLines.push(`      condition: service_started`);
  }

  return indentEntry(
    `${svc.name}_rest_api:\n` +
      `  build:\n` +
      `    context: ./${svc.name}/backend\n` +
      `    target: rest-api-dev\n` +
      `    dockerfile: Dockerfile\n` +
      `  container_name: ${projectName}-${svc.name}_rest_api\n` +
      `  restart: unless-stopped\n` +
      `  environment:\n` +
      envLines.join('\n') +
      '\n' +
      `  ports:\n` +
      `    - "${svc.backend.port}:${svc.backend.port}"\n` +
      `  volumes:\n` +
      `    - ./${svc.name}/backend:/app:cached\n` +
      `    - /app/node_modules\n` +
      `  depends_on:\n` +
      dependsLines.join('\n') +
      '\n' +
      `  env_file:\n` +
      `    - ./${svc.name}/backend/.env\n`
  );
}

function renderServiceEventQueueBlock(
  svc: ServiceEntry,
  projectName: string,
  _mode: 'dev' | 'prod'
): string {
  const upper = envPrefix(svc.name);
  const defaultDbName = `${projectName}_${svc.name}`.replace(/-/g, '_');

  return indentEntry(
    `${svc.name}_event_queue:\n` +
      `  build:\n` +
      `    context: ./${svc.name}/backend\n` +
      `    target: event-queue-dev\n` +
      `    dockerfile: Dockerfile\n` +
      `  container_name: ${projectName}-${svc.name}_event_queue\n` +
      `  restart: unless-stopped\n` +
      `  environment:\n` +
      `    NODE_ENV: development\n` +
      `    DATABASE_URL: postgresql://\${${upper}_DB_USER:-postgres}:\${${upper}_DB_PASSWORD}@${svc.name}_db:5432/\${${upper}_DB_NAME:-${defaultDbName}}\n` +
      `    LOG_LEVEL: debug\n` +
      `    REDIS_HOST: ${svc.name}_redis\n` +
      `    REDIS_PORT: 6379\n` +
      `    REDIS_PASSWORD: \${${upper}_REDIS_PASSWORD:-redis-password}\n` +
      `  volumes:\n` +
      `    - ./${svc.name}/backend:/app:cached\n` +
      `    - /app/node_modules\n` +
      `  depends_on:\n` +
      `    ${svc.name}_db:\n` +
      `      condition: service_healthy\n` +
      `    ${svc.name}_redis:\n` +
      `      condition: service_healthy\n` +
      `  env_file:\n` +
      `    - ./${svc.name}/backend/.env\n`
  );
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Uppercase service name with dashes converted to underscores, used as the
 * env-var prefix: `scout` → `SCOUT`, `my-service` → `MY_SERVICE`.
 */
function envPrefix(serviceName: string): string {
  return serviceName.toUpperCase().replace(/-/g, '_');
}

/**
 * Indent every line of a rendered block by two spaces so it sits inside
 * the `services:` top-level map. Preserves trailing newlines.
 */
function indentEntry(block: string): string {
  return block
    .split('\n')
    .map((line) => (line.length > 0 ? '  ' + line : line))
    .join('\n');
}

// Mark `YAML` as used (placeholder for future fine-grained serialization).
void YAML;
