import path from 'path';
import fs from 'fs-extra';
import chalk from 'chalk';

import { requireProjectRoot } from '../utils/project-root.js';
import { loadStackrConfig, saveStackrConfig } from '../utils/config-file.js';
import { readStackrVersion } from '../utils/version.js';
import {
  entityNames,
  validateEntityName,
  renderEntitySchemaTs,
  renderEntityRepository,
  renderEntityServiceTs,
  type EntityNames,
} from '../generators/entity-codegen.js';
import { addEntityTableDrizzle, addEntityModelPrisma } from '../utils/ast-merge/entity-merge.js';
import { getSchema } from '@mrleebo/prisma-ast';
import type { PendingMigration } from '../types/config-file.js';

export interface AddEntityOptions {
  verbose?: boolean;
}

function verboseLog(verbose: boolean, msg: string): void {
  if (verbose) console.log(chalk.gray(`  ${msg}`));
}

/** Same migration command add-service prints (replicated to avoid coupling). */
function ormMigrationCommand(
  pm: 'npm' | 'yarn' | 'bun',
  orm: 'prisma' | 'drizzle',
  serviceName: string
): string {
  const run = pm === 'npm' ? 'npm run' : pm === 'yarn' ? 'yarn' : 'bun run';
  if (orm === 'drizzle') {
    return `cd ${serviceName}/backend && ${run} drizzle-kit generate && ${run} drizzle-kit migrate`;
  }
  return `cd ${serviceName}/backend && ${run} prisma migrate dev`;
}

/**
 * `stackr add entity <service> <entity>` — correct-by-construction codegen.
 *
 * Writes `domain/<entity>/{schema,repository,service}.ts` AND AST-merges the
 * ORM table into the service's schema so the generated repository type-checks.
 * Follows the add-service discipline: everything is decided/computed in memory
 * (Phase A–C) before any disk mutation, and `stackr.config.json` is saved LAST
 * so an interrupted run leaves the config as the reliable completion indicator.
 */
export async function runAddEntity(
  serviceName: string,
  entityRaw: string,
  options: AddEntityOptions = {}
): Promise<void> {
  const verbose = Boolean(options.verbose);

  // =========================================================================
  // Phase A — read-only validation
  // =========================================================================
  const root = await requireProjectRoot(process.cwd());
  verboseLog(verbose, `Project root: ${root}`);
  const config = await loadStackrConfig(root);

  const service = config.services.find((s) => s.name === serviceName);
  if (!service) {
    const known = config.services.map((s) => s.name).join(', ') || '(none)';
    throw new Error(
      `No service named "${serviceName}" in stackr.config.json. Known services: ${known}.`
    );
  }

  const nameCheck = validateEntityName(entityRaw);
  if (!nameCheck.valid) {
    throw new Error(`Invalid entity name "${entityRaw}": ${nameCheck.error}`);
  }
  const names: EntityNames = entityNames(entityRaw);
  const orm = config.orm;
  const pm = config.packageManager;

  const domainDir = path.join(root, serviceName, 'backend', 'domain', names.folder);
  if (await fs.pathExists(domainDir)) {
    throw new Error(
      `Entity directory ${path.relative(root, domainDir)}/ already exists. ` +
        `Pick a different name or remove the existing directory first.`
    );
  }

  const schemaRel =
    orm === 'drizzle'
      ? path.join(serviceName, 'backend', 'drizzle', 'schema.ts')
      : path.join(serviceName, 'backend', 'prisma', 'schema.prisma');
  const schemaPath = path.join(root, schemaRel);
  if (!(await fs.pathExists(schemaPath))) {
    throw new Error(
      `Expected the ${orm} schema at ${schemaRel}, but it does not exist. ` +
        `Is "${serviceName}" a backend service generated by stackr?`
    );
  }

  // =========================================================================
  // Phase B — compute everything in memory (merge throws on collision)
  // =========================================================================
  const schemaSource = await fs.readFile(schemaPath, 'utf-8');
  const mergedSchema =
    orm === 'drizzle'
      ? addEntityTableDrizzle(schemaSource, names)
      : addEntityModelPrisma(schemaSource, names);

  const files: { abs: string; contents: string }[] = [
    { abs: path.join(domainDir, 'schema.ts'), contents: renderEntitySchemaTs(names) },
    { abs: path.join(domainDir, 'repository.ts'), contents: renderEntityRepository(orm, names) },
    { abs: path.join(domainDir, 'service.ts'), contents: renderEntityServiceTs(names) },
  ];

  // =========================================================================
  // Phase C — dry-run validation
  // =========================================================================
  // ts-morph already parsed the Drizzle schema; re-parse the merged Prisma
  // schema to catch any structural breakage before touching disk.
  if (orm === 'prisma') {
    try {
      getSchema(mergedSchema);
    } catch (err) {
      throw new Error(
        `Planned ${schemaRel} fails to parse after merge: ${(err as Error).message}. Aborting.`
      );
    }
  }

  // =========================================================================
  // Phase D — commit
  // =========================================================================
  // 1. New domain trio (a brand-new dir — never clobbers existing files).
  await fs.ensureDir(domainDir);
  for (const f of files) {
    await fs.writeFile(f.abs, f.contents, 'utf-8');
  }

  // 2. Merged ORM schema — temp + atomic rename so a crash can't truncate it.
  const tmpSchema = `${schemaPath}.stackr-tmp`;
  await fs.writeFile(tmpSchema, mergedSchema, 'utf-8');
  await fs.move(tmpSchema, schemaPath, { overwrite: true });

  // 3. Pending migration — the schema changed; record the command + sentinel.
  const pending: PendingMigration = {
    service: serviceName,
    reason: `added ${names.snake} table (stackr add entity ${serviceName} ${entityRaw})`,
    createdAt: new Date().toISOString(),
    createdBy: readStackrVersion(),
    command: ormMigrationCommand(pm, orm, serviceName),
  };
  config.pendingMigrations = [...(config.pendingMigrations ?? []), pending];

  // 4. Save config LAST.
  await saveStackrConfig(root, config);

  printEntityNextSteps(serviceName, names, pending.command);
}

function printEntityNextSteps(serviceName: string, names: EntityNames, migrateCmd: string): void {
  console.log();
  console.log(chalk.green(`✨ Entity "${names.folder}" added to "${serviceName}"`));
  console.log(
    chalk.gray(`   Scaffolded ${serviceName}/backend/domain/${names.folder}/{schema,repository,service}.ts`)
  );
  console.log(chalk.gray(`   Merged the \`${names.snake}\` table into the ${serviceName} ORM schema.`));
  console.log();
  console.log(chalk.bold('Next steps:'));
  console.log(chalk.yellow('  ⚠  Schema changed — run the migration, then ack the sentinel:'));
  console.log(`     ${migrateCmd}`);
  console.log(`     stackr migrations ack ${serviceName}`);
  console.log(
    chalk.gray(
      `  • Wire ${names.camel} into a route under ${serviceName}/backend/controllers/rest-api/routes/`
    )
  );
  console.log(chalk.gray('  • Keep the handler thin and import the generated TypeBox schema.'));
  console.log();
}
