import fs from 'fs-extra';
import path from 'path';
import { STACKR_CONFIG_FILENAME } from '../types/config-file.js';

/**
 * Walk upward from `startDir` looking for `stackr.config.json`. Returns the
 * directory containing the marker file, or `null` if the walk reaches the
 * filesystem root without finding one.
 *
 * Phase 1 does not invoke this at runtime (no `stackr` binary exists yet),
 * but it's part of the plumbing that phase 2 and 3 consume — and unit tests
 * exercise it so we can lock the behavior in now.
 */
export async function findProjectRoot(startDir: string): Promise<string | null> {
  let current = path.resolve(startDir);

  // path.parse(root).root === root on every platform, so comparing against
  // the parsed root gives us a reliable filesystem-root sentinel that works
  // for both POSIX (`/`) and Windows (`C:\`) paths.
  while (true) {
    const candidate = path.join(current, STACKR_CONFIG_FILENAME);
    if (await fs.pathExists(candidate)) {
      return current;
    }

    const parent = path.dirname(current);
    if (parent === current) {
      return null;
    }
    current = parent;
  }
}

/**
 * Like `findProjectRoot`, but throws a clear error if no config file is
 * found. Used by `stackr` subcommands that only make sense inside a
 * generated project.
 */
export async function requireProjectRoot(startDir: string): Promise<string> {
  const root = await findProjectRoot(startDir);
  if (root === null) {
    throw new Error(
      'Not inside a stackr project. Run this command from within a directory generated by create-stackr.'
    );
  }
  return root;
}
